tracer:
  property: "I AM ORGANIZATION SERVICE DEV"

management:
  endpoint:
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"


security:
  oauth2: 
    resource:
      userInfoUri: "http://localhost:8901/user"
spring:      
  profiles:
    active: "dev"
  jpa:
    database: "POSTGRESQL"
    show-sql: "true"
  datasource:
    url: "jdbc:postgresql://organizationdb:5432/eagle_eye_dev"
    platform: "postgres"
    username: "postgres_dev"
    password: "postgr@s_dev"
    driverClassName: "org.postgresql.Driver"
    tomcat:
      test-while-idle: "true"
      validation-query: "SELECT 1"
redis:
  server: "redis"
  port: "6379"
