tracer:
  property: I AM ORGANIZATION SERVICE PROD

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
spring:
  application:
    name: organizationservice
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    url: jdbc:postgresql://database:5432/eagle_eye_prod
    platform: postgres
    username: postgres_prod
      password: postgr@s_prod
    driverClassName: org.postgresql.Driver
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
redis:
  server: redis
  port: 6379