tracer:
  property: "I AM ORGANIZATION SERVICE DEV"

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: organizationservice
  profiles:
    active: "dev"
  jpa:
    database: "POSTGRESQL"
    show-sql: "true"
  datasource:
    url: "jdbc:postgresql://database:5432/eagle_eye_dev"
    platform: "postgres"
    username: "postgres_dev"
    password: "postgr@s_dev"
    driverClassName: "org.postgresql.Driver"
    tomcat:
      test-while-idle: "true"
      validation-query: "SELECT 1"
redis:
  server: "redis"
  port: "6379"
