tracer:
  property: I AM THE ORGANIZATION SERVICE DEFAULT

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: organizationservice
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    url: jdbc:postgresql://database:5432/eagle_eye_local
    platform: postgres
    username: postgres
    password: postgr@s
    driverClassName: org.postgresql.Driver
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1