tracer:
    property: I AM GATEWAY SERVER DEV

spring:
    cloud:
        gateway:
            discovery:
                locator: #A
                    enabled: true 
                    lowerCaseServiceId: true