tracer:
    property: I AM GATEWAY SERVICE

server:
    port: 8072
eureka:
    instance:
        preferIpAddress: true 
    client:
        registerWithEureka: true 
        fetchRegistry: true 
        serviceUrl:
            defaultZone: http://eurekaserver:8070/eureka/
spring:
    application:
        name: gateway-server
    cloud:
        gateway:
            discovery:
                locator: #A
                    enabled: true 
                    lowerCaseServiceId: true