tracer:
    property: I AM GATEWAY SERVER DEV

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  profiles:
    active: dev
  cloud:
    gateway:
      discovery:
        locator: #A
          enabled: true 
          lowerCaseServiceId: true
        routes:
          - id: organization-service #A
            uri: lb://organizationservice #B 
            predicates: #C
            - Path=/organization/**
            filters: #D
            - RewritePath=/organization/(?<path>.*), /$\{path} #E
          - id: licensing-service #A
            uri: lb://licensingservice #B 
            predicates: #C
            - Path=/licensing/**
            filters: #D
            - RewritePath=/licensing/(?<path>.*), /$\{path} #E

