tracer:
    property: I AM GATEWAY SERVER DEV

management:
  endpoint:
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

spring:
 cloud:
  gateway: 
    discovery:
      locator: # discovery locator enables automated mapping whereby
        enabled: true # gateway exposes the serviceId only if the service is running
        lowerCaseServiceId: true # If we define routes manually (as below), the one we defined will always show even if the service is not available. remove the locator config to stop automated mapping
    routes: # even if 
    - id: licensing-service #A
      uri: lb://licensingservice #B 
      predicates: #C
      - Path=/licensing/**
      filters: #D
      - RewritePath=/licensing/(?<path>.*), /$\{path} #E
    - id: organization-service #A
      uri: lb://organizationservice #B 
      predicates: #C
      - Path=/organization/**
      filters: #D
      - RewritePath=/organization/(?<path>.*), /$\{path} #E

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2500

# spring:
#   profiles:
#     active: dev
#   cloud:
#     gateway:
#       discovery:
#         locator: #A
#           enabled: true 
#           lower-case-service-id: true
#         routes:
#           - id: organization #A
#             uri: lb://organizationservice #B 
#             predicates: #C
#             - Path=/organization/**
#             filters: #D
#             - RewritePath=/organization/(?<path>.*), /$\{path} #E
#           - id: license #A
#             uri: lb://licensingservice #B 
#             predicates: #C
#             - Path=/licensing/**
#             filters: #D
#             - RewritePath=/licensing/(?<path>.*), /$\{path} #E

