tracer:
    property: I AM GATEWAY SERVICE

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
    cloud:
        gateway:
            discovery:
                locator: #A
                    enabled: true 
                    lowerCaseServiceId: true