tracer:
    property: I AM GATEWAY SERVER DEV

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  profiles:
    active: dev
  cloud:
    gateway:
      discovery:
        locator: #A
          enabled: true 
          lowerCaseServiceId: true

