tracer:
    property: I AM GATEWAY SERVICE

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
    cloud:
        gateway:
            discovery:
                locator: #A
                    enabled: true 
                    lowerCaseServiceId: true