tracer:
    property: I AM GATEWAY SERVER DEV

management:
  endpoint:
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

spring:
 gateway: 
  discovery:
    locator:
      enabled: true
      lowerCaseServiceId: true 
    routes:
    - id: licensing-service #A
      uri: lb://licensingservice #B 
      predicates: #C
      - Path=/licensing/**
      filters: #D
      - RewritePath=/licensing/(?<path>.*), /$\{path} #E
    - id: organization-service #A
      uri: lb://organizationservice #B 
      predicates: #C
      - Path=/organization/**
      filters: #D
      - RewritePath=/organization/(?<path>.*), /$\{path} #E

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2500

# spring:
#   profiles:
#     active: dev
#   cloud:
#     gateway:
#       discovery:
#         locator: #A
#           enabled: true 
#           lower-case-service-id: true
#         routes:
#           - id: organization #A
#             uri: lb://organizationservice #B 
#             predicates: #C
#             - Path=/organization/**
#             filters: #D
#             - RewritePath=/organization/(?<path>.*), /$\{path} #E
#           - id: license #A
#             uri: lb://licensingservice #B 
#             predicates: #C
#             - Path=/licensing/**
#             filters: #D
#             - RewritePath=/licensing/(?<path>.*), /$\{path} #E

