tracer:
  property: I AM PRODUCTION

management:
  endpoints:
    web:
      exposure:
        include: "*"


spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    url: jdbc:postgresql://database:5434/eagle_eye_prod
    platform: postgres
    username: postgres_prod
      password: postgr@s_prod
    driverClassName: org.postgresql.Driver
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
redis:
  server: redis
  port: 6379

